name: CI

# Events that trigger workflow
on:
  # Runs on all pushes to branches
  push:
  # Runs on all PRs
  pull_request:
  # Runs every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Manual Dispatch
  workflow_dispatch:

jobs:
  run-cace:
    runs-on: ubuntu-22.04
    name: Run CACE
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      # Run CACE on the design
      - name: Run CACE for simplest_analog_switch_ena1v8
        if: success() || failure()
        uses: efabless/cace-action@main
        with:
          pdk_family: 'sky130'
          cace_datasheet: 'cace/simplest_analog_switch_ena1v8.yaml'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run CACE for simple_analog_switch_ena1v8
        if: success() || failure()
        uses: efabless/cace-action@main
        with:
          pdk_family: 'sky130'
          cace_datasheet: 'cace/simple_analog_switch_ena1v8.yaml'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run CACE for isolated_switch_ena1v8
        if: success() || failure()
        uses: efabless/cace-action@main
        with:
          pdk_family: 'sky130'
          cace_datasheet: 'cace/isolated_switch_ena1v8.yaml'
          token: ${{ secrets.GITHUB_TOKEN }}

      # Upload artifacts
      - name: Upload Artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: runs
          path: |
            ${{ github.workspace }}/runs/

      # Add summary
      - name: Add Markdown to Step Summary
        if: success() || failure()
        run: cat runs/*/summary.md >> $GITHUB_STEP_SUMMARY
